from deepface import DeepFace

al_results = []
nm_results = []

al_images = [
    "https://www.legislature.state.al.us/pdf/house/members/Pettus_1.png",
    "https://www.legislature.state.al.us/pdf/house/members/Harrison_2.png",
    "https://www.legislature.state.al.us/pdf/house/members/Underwood_3.png",
    "https://www.legislature.state.al.us/pdf/house/members/Moore_4.png",
    "https://www.legislature.state.al.us/pdf/house/members/Crawford_5.png",
    "https://www.legislature.state.al.us/pdf/house/members/Whitt_6.png",
    "https://www.legislature.state.al.us/pdf/house/members/Yarbrough_7.png",
    "https://www.legislature.state.al.us/pdf/house/members/Collins_8.png",
    "https://www.legislature.state.al.us/pdf/house/members/Stadthagen_9.png",
    "https://www.legislature.state.al.us/pdf/house/members/Shedd_11.png",
    "https://www.legislature.state.al.us/pdf/house/members/Harbison_12.png",
    "https://www.legislature.state.al.us/pdf/house/members/Woods_13.png",
    "https://www.legislature.state.al.us/pdf/house/members/Wadsworth_14.png",
    "https://www.legislature.state.al.us/pdf/house/members/Hulsey_15.png",
    "https://www.legislature.state.al.us/pdf/house/members/Brinyark_16.png",
    "https://www.legislature.state.al.us/pdf/house/members/Estes_17.png",
    "https://www.legislature.state.al.us/pdf/house/members/Kiel_18.png",
    "https://www.legislature.state.al.us/pdf/house/members/Hall_19.png",
    "https://www.legislature.state.al.us/pdf/house/members/Lomax_20.png",
    "https://www.legislature.state.al.us/pdf/house/members/Reynolds_21.png",
    "https://www.legislature.state.al.us/pdf/house/members/Whorton_22.png",
    "https://www.legislature.state.al.us/pdf/house/members/Kirkland_23.png",
    "https://www.legislature.state.al.us/pdf/house/members/Ledbetter_24.png",
    "https://www.legislature.state.al.us/pdf/house/members/Rigsby_25.png",
    "https://www.legislature.state.al.us/pdf/house/members/Colvin_26.png",
    "https://www.legislature.state.al.us/pdf/house/members/Butler_28.png",
    "https://www.legislature.state.al.us/pdf/house/members/Gidley_29.png",
    "https://www.legislature.state.al.us/pdf/house/members/Stubbs_31.png",
    "https://www.legislature.state.al.us/pdf/house/members/Boyd_32.png",
    "https://www.legislature.state.al.us/pdf/house/members/Robbins_33.png",
    "https://www.legislature.state.al.us/pdf/house/members/Standridge_34.png",
    "https://www.legislature.state.al.us/pdf/house/members/Hurst_35.png",
    "https://www.legislature.state.al.us/pdf/house/members/Wood_36.png",
    "https://www.legislature.state.al.us/pdf/house/members/Fincher_37.png",
    "https://www.legislature.state.al.us/pdf/house/members/Wood_38.png",
    "https://www.legislature.state.al.us/pdf/house/members/Shaver_39.png",
    "https://www.legislature.state.al.us/pdf/house/members/Robertson_40.png",
    "https://www.legislature.state.al.us/pdf/house/members/Ellis_41.png",
    "https://www.legislature.state.al.us/pdf/house/members/Smith_42.png",
    "https://www.legislature.state.al.us/pdf/house/members/Mooney_43.png",
    "https://www.legislature.state.al.us/pdf/house/members/Garrett_44.png",
    "https://www.legislature.state.al.us/pdf/house/members/DuBose_45.png",
    "https://www.legislature.state.al.us/pdf/house/members/Faulkner_46.png",
    "https://www.legislature.state.al.us/pdf/house/members/Shaw_47.png",
    "https://www.legislature.state.al.us/pdf/house/members/Carns_48.png",
    "https://www.legislature.state.al.us/pdf/house/members/Bedsole_49.png",
    "https://www.legislature.state.al.us/pdf/house/members/Hill_50.png",
    "https://www.legislature.state.al.us/pdf/house/members/Treadaway_51.png",
    "https://www.legislature.state.al.us/pdf/house/members/Rogers_52.png",
    "https://www.legislature.state.al.us/pdf/house/members/Daniels_53.png",
    "https://www.legislature.state.al.us/pdf/house/members/Rafferty_54.png",
    "https://www.legislature.state.al.us/pdf/house/members/Hendrix_55.png",
    "https://www.legislature.state.al.us/pdf/house/members/Sellers_57.png",
    "https://www.legislature.state.al.us/pdf/house/members/Hollis_58.png",
    "https://www.legislature.state.al.us/pdf/house/members/Moore_59.png",
    "https://www.legislature.state.al.us/pdf/house/members/Givan_60.png",
    "https://www.legislature.state.al.us/pdf/house/members/Bolton_61.png",
    "https://www.legislature.state.al.us/pdf/house/members/Almond_63.png",
    "https://www.legislature.state.al.us/pdf/house/members/Givens_64.png",
    "https://www.legislature.state.al.us/pdf/house/members/Easterbrook_65.png",
    "https://www.legislature.state.al.us/pdf/house/members/Baker_66.png",
    "https://www.legislature.state.al.us/pdf/house/members/Chestnut_67.png",
    "https://www.legislature.state.al.us/pdf/house/members/Jackson_68.png",
    "https://www.legislature.state.al.us/pdf/house/members/Lawrence_69.png",
    "https://www.legislature.state.al.us/pdf/house/members/England_70.png",
    "https://www.legislature.state.al.us/pdf/house/members/McCampbell_71.png",
    "https://www.legislature.state.al.us/pdf/house/members/Travis_72.png",
    "https://www.legislature.state.al.us/pdf/house/members/Paschal_73.png",
    "https://www.legislature.state.al.us/pdf/house/members/Ensler_74.png",
    "https://www.legislature.state.al.us/pdf/house/members/Ingram_75.png",
    "https://www.legislature.state.al.us/pdf/house/members/mcclammy.png",
    "https://www.legislature.state.al.us/pdf/house/members/Morris_77.png",
    "https://www.legislature.state.al.us/pdf/house/members/kenyatte-hassell.png",
    "https://www.legislature.state.al.us/pdf/house/members/Lovvorn_79.png",
    "https://www.legislature.state.al.us/pdf/house/members/Blackshear_80.png",
    "https://www.legislature.state.al.us/pdf/house/members/Oliver_81.png",
    "https://www.legislature.state.al.us/pdf/house/members/Warren_82.png",
    "https://www.legislature.state.al.us/pdf/house/members/Gray_83.png",
    "https://www.legislature.state.al.us/pdf/house/members/Forte_84.png",
    "https://www.legislature.state.al.us/pdf/house/members/Rehm_85.png",
    "https://www.legislature.state.al.us/pdf/house/members/Lee_86.png",
    "https://www.legislature.state.al.us/pdf/house/members/Sorrells_87.png",
    "https://www.legislature.state.al.us/pdf/house/members/Starnes_88.png",
    "https://www.legislature.state.al.us/pdf/house/members/Paramore_89.png",
    "https://www.legislature.state.al.us/pdf/house/members/Sells_90.png",
    "https://www.legislature.state.al.us/pdf/house/members/Marques_91.png",
    "https://www.legislature.state.al.us/pdf/house/members/Hammett_92.png",
    "https://www.legislature.state.al.us/pdf/house/members/Clouse_93.png",
    "https://www.legislature.state.al.us/pdf/house/members/Fidler_94.png",
    "https://www.legislature.state.al.us/pdf/house/members/Holk-Jones_95.png",
    "https://www.legislature.state.al.us/pdf/house/members/Simpson_96.png",
    "https://www.legislature.state.al.us/pdf/house/members/Clarke_97.png",
    "https://www.legislature.state.al.us/pdf/house/members/Bracy_98.png",
    "https://www.legislature.state.al.us/pdf/house/members/Jones_99.png",
    "https://www.legislature.state.al.us/pdf/house/members/Shirey_100.png",
    "https://www.legislature.state.al.us/pdf/house/members/Pringle_101.png",
    "https://www.legislature.state.al.us/pdf/house/members/Stringer_102.png",
    "https://www.legislature.state.al.us/pdf/house/members/Drummond_103.png",
    "https://www.legislature.state.al.us/pdf/house/members/Wilcox_104.png",
    "https://www.legislature.state.al.us/pdf/house/members/Brown_105.png"
    ]

nm_images = [
    "https://www.nmlegis.gov/Images/Legislators/House/HMONR.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HDUNC.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HLANE.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HALLI.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HJOHD.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HALCO.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HMIRA.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HBACB.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HLUND.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HROMA.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HMARJ.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HDELA.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HROYB.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HHOCH.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HGURR.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HBORR.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HCHAS.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HANYA.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HDIXO.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HSARI.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HLORD.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HMAAL.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HTHOE.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HPARA.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HCHAL.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HMATT.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HHEPA.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HGARR.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HFIGU.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HREHM.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HJONJ.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HCADA.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HLARA.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HRUBI.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HSMAL.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HFERJ.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HJARA.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HTERR.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HSAJO.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HHERS.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HORTE.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HCHAN.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HCATE.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HSERR.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HROAN.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HSZCZ.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HLUTA.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HARMG.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HMCQU.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HBLOC.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HGADO.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HMADR.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HTOWJ.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HBROW.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HVINC.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HHARP.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HEZZE.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HHEMB.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HPETT.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HSCOT.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HZAMO.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HREEB.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HLENT.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HMASO.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HLITC.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HGAHA.jpg",
    "https://www.nmlegis.gov/Images/Legislators/House/HCAST.jpg"
    ]

for image in al_images:
  result = DeepFace.analyze(
    img_path = image,
    actions = ['race'],
  )
  data = [(item['dominant_race'], item['face_confidence']) for item in result]
  data.append(image.split('/')[-1].split('.')[0])
  al_results.append(data)

for image in nm_images:
  result = DeepFace.analyze(
    img_path = image,
    actions = ['race'],
  )
  data = [(item['dominant_race'], item['face_confidence']) for item in result]
  data.append(image.split('/')[-1].split('.')[0])
  nm_results.append(data)

for result in al_results:
  print(' '.join(map(str, result)))

for result in nm_results:
  print(' '.join(map(str, result)))